package records

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/samlet/record-hub/server/internal/modules/identity"
)

// IndexDirection is deliberately limited to Mongo's two scalar sort
// directions. The API never accepts an arbitrary index expression.
type IndexDirection string

const (
	IndexAscending  IndexDirection = "asc"
	IndexDescending IndexDirection = "desc"
)

const maxIndexesPerTable = 16

var indexPhysicalNamePattern = regexp.MustCompile(`^record_data_[a-f0-9]{16}$`)

// IndexDefinition describes one bounded, administrator-approved index over a
// published schema property. Name is generated by the server and is exposed
// only so operators can correlate metadata with the physical Mongo index.
type IndexDefinition struct {
	ID          string               `bson:"_id" json:"id"`
	TenantID    string               `bson:"tenantId" json:"tenantId"`
	WorkspaceID string               `bson:"workspaceId" json:"workspaceId"`
	TableID     string               `bson:"tableId" json:"tableId"`
	Field       string               `bson:"field" json:"field"`
	Direction   IndexDirection       `bson:"direction" json:"direction"`
	Name        string               `bson:"name" json:"name"`
	Version     int64                `bson:"version" json:"version"`
	CreatedBy   identity.IdentityKey `bson:"createdBy" json:"createdBy"`
	CreatedAt   time.Time            `bson:"createdAt" json:"createdAt"`
	UpdatedAt   time.Time            `bson:"updatedAt" json:"updatedAt"`
}

func (definition IndexDefinition) Validate() error {
	if strings.TrimSpace(definition.ID) == "" || strings.TrimSpace(definition.TenantID) == "" || strings.TrimSpace(definition.WorkspaceID) == "" || strings.TrimSpace(definition.TableID) == "" || strings.TrimSpace(definition.Field) == "" {
		return errors.New("index id, tenant, workspace, table, and field are required")
	}
	if err := validateViewField(definition.Field); err != nil {
		return fmt.Errorf("index field: %w", err)
	}
	field := strings.TrimPrefix(strings.TrimSpace(definition.Field), "data.")
	if field == "" || strings.Contains(field, ".") || strings.HasPrefix(field, "_") {
		return errors.New("index field must be a top-level published schema property")
	}
	if definition.Direction != IndexAscending && definition.Direction != IndexDescending {
		return errors.New("index direction must be asc or desc")
	}
	if definition.Name != "" {
		if !indexPhysicalNamePattern.MatchString(definition.Name) || definition.Name != physicalIndexName(field, definition.Direction) {
			return errors.New("index name is invalid or does not match the field and direction")
		}
	}
	if definition.Version < 1 {
		return errors.New("index version must be positive")
	}
	if definition.CreatedBy.Issuer == "" || definition.CreatedBy.Subject == "" || definition.CreatedAt.IsZero() || definition.UpdatedAt.IsZero() {
		return errors.New("index creator and timestamps are required")
	}
	return nil
}

func normalizeIndexField(field string) string {
	return strings.TrimPrefix(strings.TrimSpace(field), "data.")
}

// physicalIndexName is deterministic and never embeds user-controlled text.
// This prevents Mongo index-name injection and keeps retries idempotent.
func physicalIndexName(field string, direction IndexDirection) string {
	digest := sha256.Sum256([]byte("data\x00" + normalizeIndexField(field) + "\x00" + string(direction)))
	return "record_data_" + hex.EncodeToString(digest[:])[:16]
}

func indexKey(field string, direction IndexDirection) string {
	return normalizeIndexField(field) + "\x00" + string(direction)
}

func isIndexEnvelopeField(field string) bool {
	switch normalizeIndexField(field) {
	case "id", "_id", "recordVersion", "schemaVersion", "createdAt", "updatedAt", "tags", "relations", "source", "projection":
		return true
	default:
		return false
	}
}
